# Generated by Django 2.1.5 on 2020-01-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='img',
            new_name='logo',
        ),
    ]
